server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - "qa"
  cloud:
    config:
      enabled: false
build:
  version: "3.0"

accounts:
  message: "Welcome to MrxBank accounts related local APIs "
  contactDetails:
    name: "Muthuraja SDE"
    email: "rajamuthu107@gmail.com"
  onCallSupport:
    - (91) 6369366095
management:
  endpoints:
    web:
      exposure:
        include: "*"


