spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to mrxbank accounts related prod APIs "
  contactDetails:
    name: "Muthuraja - Product Owner"
    email: "rajamuthu107@gmail.com"
  onCallSupport:
    - (91) 6369366095
